# Generated by Django 2.0.5 on 2018-05-07 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startrecord',
            name='destination',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='startrecord',
            name='source',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
