# Generated by Django 2.0.5 on 2018-05-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelphoneRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standing_charge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('charge_minute', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('type', models.CharField(choices=[('standard', 'standard'), ('reduced', 'reduced')], max_length=8)),
            ],
        ),
    ]
