# Generated by Django 2.0.5 on 2018-05-06 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.EndRecord')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.StartRecord')),
            ],
        ),
    ]
